name: todoapp
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  dio: ^5.8.0+1
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.2.1
  get_it: ^8.0.3
  go_router: ^16.0.0
  provider: ^6.1.5
  shared_preferences: ^2.5.3
  flutter_feather_icons: ^2.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/illustrations/
    - .env
  fonts:
  - family: Comic
    fonts:
      - asset: assets/fonts/comic/ComicRelief-Regular.ttf
        weight: 100
      - asset: assets/fonts/comic/ComicRelief-Bold.ttf
        weight: 200
  - family: Inter
    fonts:
      - asset: assets/fonts/inter/Inter_18pt-Thin.ttf
        weight: 100
      - asset: assets/fonts/inter/Inter_18pt-ExtraLight.ttf
        weight: 200
      - asset: assets/fonts/inter/Inter_18pt-Light.ttf
        weight: 300
      - asset: assets/fonts/inter/Inter_18pt-Regular.ttf
        weight: 400
      - asset: assets/fonts/inter/Inter_18pt-Medium.ttf
        weight: 500
      - asset: assets/fonts/inter/Inter_18pt-SemiBold.ttf
        weight: 600
      - asset: assets/fonts/inter/Inter_18pt-Bold.ttf
        weight: 700
      - asset: assets/fonts/inter/Inter_18pt-ExtraBold.ttf
        weight: 800
      - asset: assets/fonts/inter/Inter_18pt-Black.ttf
        weight: 900